services:
  ingestion:
    build:
      context: ./ingestion
      dockerfile: Dockerfile.pyIngestion
    image: ingestion:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kafka-net
    restart: "no"
  ingestionMAD:
    build:
      context: ./ingestion_datosMAD
      dockerfile: Dockerfile.pyIngestionMAD
    image: ingestion_datosmad:latest
    env_file: .env
    environment:
      - API_URL=http://api:5000
    networks:
      - kafka-net
    restart: "no"
  alertas_pob_general:
    build:
      context: ./productores/pob_general/alertas
      dockerfile: Dockerfile.pyAlertas
    image: alertas_pob_general:latest
    depends_on:
      - kafka
    networks:
      - kafka-net
    tty: true
    restart: "no"
  alertas_pob_riesgo:
    build:
      context: ./productores/pob_riesgo/alertas
      dockerfile: Dockerfile.pyAlertas
    image: alertas_pob_riesgo:latest
    depends_on:
      - kafka
    networks:
      - kafka-net
    tty: true
    restart: "no"
  datos_pob_general:
    build:
      context: ./productores/pob_general/datos
      dockerfile: Dockerfile.pyDatos
    image: datos_pob_general:latest
    depends_on:
      - kafka
    networks:
      - kafka-net
    tty: true
    restart: "no"
  datos_pob_riesgo:
    build:
      context: ./productores/pob_riesgo/datos
      dockerfile: Dockerfile.pyDatos
    image: datos_pob_riesgo:latest
    depends_on:
      - kafka
    networks:
      - kafka-net
    tty: true
    restart: "no"

  # plotly:
  #   build:
  #     context: ./plotly
  #     dockerfile: Dockerfile.pyPlotly
  #   image: plotly:latest
  #   env_file: .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - kafka-net
  #   restart: "no"
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile.pyDBT
    image: dbt:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kafka-net
    #tty: true
    restart: unless-stopped
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kafka-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 2s
      timeout: 2s
      retries: 15
    restart: "no"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    healthcheck:
      test: echo srvr | nc localhost 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - kafka-net
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:29092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - kafka-net

  topico_alertas_pob_generales:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c " kafka-topics --create --topic alertas_pob_generales --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --if-not-exists"
    networks:
      - kafka-net
  topico_alertas_pob_riesgo:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c " kafka-topics --create --topic alertas_pob_riesgo --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --if-not-exists"
    networks:
      - kafka-net
  topico_datos_pob_general:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c " kafka-topics --create --topic datos_pob_general --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --if-not-exists"
    networks:
      - kafka-net
  topico_datos_pob_riesgo:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c " kafka-topics --create --topic datos_pob_riesgo --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --if-not-exists"
    networks:
      - kafka-net

  pgadmin:
    container_name: pgadmim
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - kafka-net
    restart: unless-stopped

  api:
    build:
      context: ./API
      dockerfile: Dockerfile.API
    image: data-project-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
volumes:
  postgres-data:


